---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Log into the Web Console
    - name: module-02
      label: Navigate to Software Updates application
    - name: module-03
      label: Examine available updates
    - name: module-04
      label: Apply security updates
    - name: module-05
      label: Apply remaining available updates
tabs:
  - name: ">_ Terminal"
    port: 443
    path: /tty1
    user: root
    host: rhel
